Repository Malagor/travel-app, pull requests merged in 2021-03, with the labels that each got.

#29 TA-04 widget weather
  package-lock.json
  src/appConstants/api.ts
  src/appConstants/colors.ts
  src/components/App/App.tsx
  src/components/Weather/Weather.tsx
  src/components/Weather/components/WeatherView.module.scss
  src/components/Weather/components/WeatherView.tsx
  src/components/Weather/index.ts
  src/components/index.ts
  src/i18n.ts
  src/locales/be/translation.json
  src/locales/en/translation.json
  src/locales/ru/translation.json
  src/types.ts
  yarn.lock
Labels: 🎯 feature

#32 TA-20 basic layout
  package.json
  src/components/App/App.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/components/Footer/Footer.tsx
  src/components/Layout/components/Footer/index.ts
  src/components/Layout/components/MenyItems/MenuItems.tsx
  src/components/Layout/components/MenyItems/index.ts
  src/components/Layout/components/index.ts
  src/components/Layout/styled.ts
  src/components/Search/Search.tsx
  src/components/Search/index.ts
  src/components/Search/styled.ts
  src/components/index.ts
  src/index.tsx
  src/modules/CountryPage/CountryPage.module.scss
  src/modules/CountryPage/CountryPage.tsx
  src/modules/CountryPage/index.ts
  src/modules/MainPage/MainPage.tsx
  src/modules/MainPage/components/CountryCard/CountryCard.tsx
  src/modules/MainPage/components/CountryCard/index.ts
  src/modules/MainPage/components/index.ts
  src/modules/MainPage/index.ts
  src/modules/MainPage/mockupDataCountries.ts
  src/modules/index.ts
  src/types.ts
Labels: 🎯 feature

#31 TA 15 add styled-components
  README.md
  package.json
  src/components/Clock/Clock.module.scss
  src/components/Clock/Clock.tsx
  src/components/Clock/styled.ts
  src/components/ErrorMessage/ErrorMessage.tsx
  src/components/ErrorMessage/styled.ts
  yarn.lock
Labels: 🛠 refactor

#30 TA-05: Currency widget
  src/appConstants/api.ts
  src/appConstants/currencyMap.ts
  src/components/CurrencyRate/CurrencyRate.module.scss
  src/components/CurrencyRate/CurrencyRate.tsx
  src/components/CurrencyRate/components/CurrencyRateView.tsx
  src/components/CurrencyRate/index.ts
  src/components/index.ts
  src/types.ts
Labels: 🎯 feature

#36 TA-21 Redux
  package.json
  src/appConstants/general.ts
  src/appConstants/index.ts
  src/components/LanguageToggle/LanguageToggle.tsx
  src/components/Layout/Layout.tsx
  src/index.tsx
  src/modules/CountryPage/CountryPage.module.scss
  src/modules/CountryPage/CountryPage.tsx
  src/modules/CountryPage/components/CountryPageView/CountryPageView.tsx
  src/modules/CountryPage/components/CountryPageView/index.ts
  src/modules/CountryPage/components/CountryPageView/styled.ts
  src/modules/CountryPage/components/index.ts
  src/modules/CountryPage/index.ts
  src/modules/MainPage/MainPage.tsx
  src/modules/MainPage/components/CountryCard/CountryCard.tsx
  src/modules/MainPage/mockupDataCountries.ts
  src/modules/MainPage/styled.ts
  src/services/database.ts
  src/services/index.ts
  src/services/initialDB.ts
  src/services/mockupDataCountries.ts
  src/store/actions.ts
  src/store/index.tsx
  src/store/initialState.ts
  src/store/reducer.ts
  src/types.ts
  yarn.lock
Labels: 🎯 feature

#38 TA-07 Video
  package-lock.json
  package.json
  src/modules/CountryPage/components/CountryPageView/CountryPageView.tsx
  src/modules/CountryPage/components/VideoPlayer/VideoPlayer.tsx
  src/modules/CountryPage/components/VideoPlayer/index.ts
  src/modules/CountryPage/components/VideoPlayer/styled.ts
  src/services/mockupDataCountries.ts
  yarn.lock
Labels: 🎯 feature

#37 Ta 06 remake
  .eslintignore
  package.json
  src/components/App/App.tsx
  src/components/Clock/Clock.tsx
  src/components/Clock/index.ts
  src/components/ClockWidget/ClockWidget.module.scss
  src/components/ClockWidget/ClockWidget.tsx
  src/components/ClockWidget/components/Clock/Clock.module.scss
  src/components/ClockWidget/components/Clock/Clock.tsx
  src/components/ClockWidget/components/Clock/index.ts
  src/components/ClockWidget/components/Clock/styled.ts
  src/components/ClockWidget/components/Date/DateString.module.scss
  src/components/ClockWidget/components/Date/DateString.tsx
  src/components/ClockWidget/components/Date/index.ts
  src/components/ClockWidget/components/DigitalWatch/DigitalWatch.module.scss
  src/components/ClockWidget/components/DigitalWatch/DigitalWatch.tsx
  src/components/ClockWidget/components/DigitalWatch/index.ts
  src/components/ClockWidget/components/index.ts
  src/components/ClockWidget/index.ts
  src/components/index.ts
  yarn.lock
Labels: 🎯 feature, 🛠 refactor

#48 TA-27 fix: fixed style clock widget and connectined in app
  src/components/ClockWidget/ClockWidget.module.scss
  src/components/ClockWidget/ClockWidget.tsx
  src/components/ClockWidget/components/Clock/Clock.tsx
  src/components/ClockWidget/components/Clock/index.ts
  src/components/ClockWidget/components/Date/DateString.module.scss
  src/components/ClockWidget/components/Date/DateString.tsx
  src/components/ClockWidget/components/Date/index.ts
  src/components/ClockWidget/components/DigitalWatch/DigitalWatch.module.scss
  src/components/ClockWidget/components/DigitalWatch/DigitalWatch.tsx
  src/components/ClockWidget/components/DigitalWatch/index.ts
  src/components/ClockWidget/components/index.ts
  src/components/ClockWidget/index.ts
  src/modules/CountryPage/components/CountryPageView/components/WidgetsPanel/WidgetsPanel.tsx
Labels: 💀❗ critical bug, 🛠 refactor

#50 TA-25 CurrencyRate refactoring
  src/appConstants/currencyMap.ts
  src/appConstants/currencyNames.ts
  src/components/CurrencyRate/CurrencyRate.module.scss
  src/components/CurrencyRate/CurrencyRate.tsx
  src/components/CurrencyRate/components/CurrencyRateView.tsx
  src/modules/CountryPage/components/CountryPageView/components/WidgetsPanel/WidgetsPanel.tsx
Labels: 🛠 refactor

#53 TA 23 conect to DB
  README.md
  firebase.json
  package.json
  src/appConstants/index.ts
  src/components/App/App.tsx
  src/components/index.ts
  src/locales/be/translation.json
  src/locales/en/translation.json
  src/locales/ru/translation.json
  src/modules/CountryPage/CountryPage.tsx
  src/modules/CountryPage/components/CountryPageView/CountryPageView.tsx
  src/modules/CountryPage/components/CountryPageView/components/VideoPlayer/VideoPlayer.tsx
  src/modules/CountryPage/components/CountryPageView/components/VideoPlayer/index.ts
  src/modules/CountryPage/components/CountryPageView/components/VideoPlayer/styled.ts
  src/modules/CountryPage/components/CountryPageView/components/WidgetsPanel/WidgetsPanel.tsx
  src/modules/CountryPage/components/CountryPageView/components/index.ts
  src/modules/MainPage/MainPage.tsx
  src/services/countriesGeo.json
  src/services/database.ts
  src/services/index.ts
  src/services/initialDB.ts
  src/services/mockupDataCountries.ts
  src/services/mongodb.ts
  src/store/actions.ts
  src/store/initialState.ts
  src/store/reducer.ts
  src/types.ts
  yarn.lock
Labels: 🎯 feature, 🔥 hot-hot-hot 🔥

#56 TA-30 refactor: correct dependencies
  package.json
  src/modules/CountryPage/components/CountryPageView/CountryPageView.tsx
  src/modules/CountryPage/components/CountryPageView/components/WidgetsPanel/WidgetsPanel.tsx
  src/modules/MainPage/MainPage.tsx
Labels: 💀❗ critical bug, 🛠 refactor

#46 TA-01 Search
  src/appConstants/index.ts
  src/components/App/App.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/components/Header/Header.tsx
  src/components/Search/Search.tsx
  src/components/Search/styled.ts
  src/locales/be/translation.json
  src/locales/en/translation.json
  src/locales/ru/translation.json
  src/modules/MainPage/MainPage.tsx
  src/store/actions.ts
  src/store/initialState.ts
  src/store/reducer.ts
  src/types.ts
Labels: 🎯 feature

#66 TA-24 made language toggle like select
  src/components/LanguageToggle/LanguageToggle.tsx
Labels: 🎯 feature, 🛠 refactor

#58 TA-31 refactor: deleted no-use services
  src/services/database.ts
  src/services/initialDB.ts
  src/services/mockupDataCountries.ts
Labels: 🛠 refactor

#62 Ta 33 rating and DB
  src/modules/CountryPage/components/CountryPageView/components/PhotoGallery/PhotoGallery.tsx
  src/services/mongodb.ts
  src/store/initialState.ts
  src/types.ts
Labels: 🎯 feature

#60 TA-32 connect search country with DB
  src/modules/MainPage/MainPage.tsx
Labels: 🎯 feature, 🛠 refactor

#69 TA-36 fix: clear old country data while reload
  src/modules/CountryPage/CountryPage.tsx
  src/modules/MainPage/MainPage.tsx
  src/modules/MainPage/components/CountryCard/CountryCard.tsx
Labels: ❗ bug, 🛠 refactor

#49 Ta 03
  src/assets/webp/mark-github-512.webp
  src/components/Layout/components/Footer/Footer.tsx
Labels: 🛠 refactor

#70 TA-29 PhotoGallery with Ratings
  package-lock.json
  package.json
  src/locales/be/translation.json
  src/locales/en/translation.json
  src/locales/ru/translation.json
  src/modules/CountryPage/components/CountryPageView/components/PhotoGallery/PhotoGallery.module.scss
  src/modules/CountryPage/components/CountryPageView/components/PhotoGallery/PhotoGallery.tsx
  src/modules/CountryPage/components/CountryPageView/components/PhotoGallery/components/NextArrow.tsx
  src/modules/CountryPage/components/CountryPageView/components/PhotoGallery/components/PrevArrow.tsx
  src/modules/CountryPage/components/CountryPageView/components/PhotoGallery/components/Slide.tsx
  src/modules/CountryPage/components/CountryPageView/components/PhotoGallery/components/index.ts
Labels: 🛠 refactor

#79 TA-39 Swap Currency Rate API Key
  src/appConstants/api.ts
Labels: 🔥 hot-hot-hot 🔥

#65 TA-09 Map
  package-lock.json
  package.json
  src/appConstants/api.ts
  src/modules/CountryPage/components/CountryPageView/CountryPageView.tsx
  src/modules/CountryPage/components/CountryPageView/components/Map/Map.tsx
  src/modules/CountryPage/components/CountryPageView/components/Map/index.ts
  src/modules/CountryPage/components/CountryPageView/components/Map/styled.ts
  src/modules/CountryPage/components/CountryPageView/components/index.ts
  src/services/countriesGeo.json
  src/types.ts
  yarn.lock
Labels: 🎯 feature

#77 TA-28 fix weather
  src/components/Weather/Weather.tsx
  src/components/Weather/components/WeatherView.module.scss
  src/components/Weather/components/WeatherView.tsx
  src/components/Weather/components/styled.ts
  src/modules/CountryPage/components/CountryPageView/components/WidgetsPanel/WidgetsPanel.tsx
Labels: ❗ bug, 🛠 refactor

#76 TA-38 fix video loading
  src/modules/CountryPage/components/CountryPageView/CountryPageView.tsx
  src/modules/CountryPage/components/CountryPageView/components/VideoPlayer/VideoPlayer.tsx
Labels: ❗ bug, 🛠 refactor

#86 TA-42 add unique keys to polygons
  src/modules/CountryPage/components/CountryPageView/components/Map/Map.tsx
Labels: ❗ bug

#74 Ta 34 createUser func
  .firebase/hosting.YnVpbGQ.cache
  .gitignore
  src/appConstants/index.ts
  src/components/LanguageToggle/LanguageToggle.tsx
  src/components/Layout/components/Header/Header.tsx
  src/components/Layout/components/Header/styled.ts
  src/services/mongodb.ts
  src/store/actions.ts
  src/store/initialState.ts
  src/store/reducer.ts
  src/types.ts
Labels: 🎯 feature

#88 TA-42 add avatar to func Create user
  src/services/mongodb.ts
Labels: 🎯 feature

#81 AT-40 transfer widgets into side panel
  src/components/ClockWidget/ClockWidget.module.scss
  src/components/ClockWidget/ClockWidget.tsx
  src/components/ErrorMessage/ErrorMessage.tsx
  src/components/ErrorMessage/styled.ts
  src/components/Layout/Layout.tsx
  src/components/Layout/components/Header/styled.ts
  src/components/Layout/components/MenyItems/MenuItems.tsx
  src/components/Layout/components/MenyItems/index.ts
  src/components/Layout/components/SideBar/SideBar.tsx
  src/components/Layout/components/SideBar/styled.ts
  src/components/Layout/components/index.ts
  src/components/Layout/styled.ts
  src/components/Weather/Weather.tsx
  src/modules/CountryPage/components/CountryPageView/CountryPageView.tsx
  src/modules/CountryPage/components/CountryPageView/components/WidgetsPanel/WidgetsPanel.tsx
  src/modules/CountryPage/components/CountryPageView/components/WidgetsPanel/index.ts
  src/modules/CountryPage/components/CountryPageView/components/WidgetsPanel/styled.ts
  src/modules/CountryPage/components/CountryPageView/components/index.ts
  src/modules/MainPage/MainPage.tsx
  src/store/initialState.ts
  src/types.ts
  yarn.lock
Labels: 🎯 feature, 🛠 refactor

#85 TA-41 added button for youtube video
  src/appConstants/index.ts
  src/assets/images/youtubeLogo.png
  src/components/Layout/components/Footer/Footer.tsx
  yarn.lock
Labels: 🎯 feature

#92 TA-43 correct action of side panel
  src/appConstants/index.ts
  src/components/Layout/Layout.tsx
  src/components/Layout/components/Header/Header.tsx
  src/components/Layout/components/SideBar/SideBar.tsx
  src/components/Layout/components/SideBar/components/MenyItems/MenuItems.tsx
  src/components/Layout/components/SideBar/components/MenyItems/index.ts
  src/components/Layout/components/SideBar/components/index.ts
  src/components/Layout/components/SideBar/styled.ts
  src/components/Layout/components/index.ts
  src/components/Search/Search.tsx
  src/components/Search/styled.ts
Labels: 🎯 feature, 🛠 refactor

#95 TA-45 add catch blocks to handle data acquisition errors
  src/modules/CountryPage/CountryPage.tsx
  src/modules/MainPage/MainPage.tsx
Labels: 🎯 feature, 🛠 refactor

#97 Ta 46 Recent Votes Table
  src/locales/be/translation.json
  src/locales/en/translation.json
  src/locales/ru/translation.json
  src/modules/CountryPage/components/CountryPageView/components/PhotoGallery/PhotoGallery.tsx
  src/modules/CountryPage/components/CountryPageView/components/PhotoGallery/components/Slide.tsx
  src/types.ts
Labels: 🎯 feature, 🛠 refactor

#101 TA-46 change weather link to https
  src/components/Weather/Weather.tsx
Labels: ❗ bug

#103 TA-47 fix map bounds setting
  src/modules/CountryPage/components/CountryPageView/components/Map/Map.tsx
Labels: ❗ bug, 🛠 refactor

#105 TA-48 fix currency widget on mobile
  src/components/CurrencyRate/CurrencyRate.module.scss
Labels: ❗ bug

#99 Ta 12-right login/registration
  database.rules.json
  package.json
  src/appConstants/firedaseConfig.ts
  src/appConstants/index.ts
  src/assets/svg/google-logo.svg.png
  src/components/App/App.tsx
  src/components/Layout/components/Header/Header.tsx
  src/components/Layout/components/Header/styled.ts
  src/components/Layout/components/SideBar/SideBar.tsx
  src/components/LoginRegistration/Registration.tsx
  src/components/LoginRegistration/index.tsx
  src/components/LoginRegistration/login.tsx
  src/components/LoginRegistration/styledRegistration.ts
  src/components/LoginRegistration/utils/signInByGoogle.ts
  src/components/index.ts
  src/locales/be/translation.json
  src/locales/en/translation.json
  src/locales/ru/translation.json
  src/modules/MainPage/MainPage.tsx
  src/store/actions.ts
  yarn.lock
Labels: 🎯 feature

#111 Ta 50
  src/components/Layout/components/SideBar/components/MenyItems/MenuItems.tsx
  src/locales/be/translation.json
  src/locales/en/translation.json
  src/locales/ru/translation.json
Labels: ❗ bug

#110 TA-53 fix: create user with current language
  src/components/LoginRegistration/Registration.tsx
Labels: ❗ bug, 🛠 refactor

#107 TA-49 feat: add save lang to DB
  src/components/LanguageToggle/LanguageToggle.tsx
  src/services/mongodb.ts
Labels: 🎯 feature, 🛠 refactor

#113 Ta 54
  src/appConstants/index.ts
  src/components/App/App.tsx
  src/components/LoginRegistration/Registration.tsx
  src/components/LoginRegistration/utils/signInByGoogle.ts
  src/locales/be/translation.json
  src/locales/en/translation.json
  src/locales/ru/translation.json
  src/modules/CountryPage/components/CountryPageView/components/PhotoGallery/components/Slide.tsx
  src/store/actions.ts
Labels: ❗ bug, 🎯 feature, 🛠 refactor
